project_id = "ojuposjetyknqoiuppiu"

[functions.feedback-chat]
verify_jwt = true

[functions.submit-lead]
verify_jwt = false

[functions.trigger-call]
verify_jwt = false

[functions.vapi-outbound-call]
verify_jwt = false

[functions.analyze-emotion]
verify_jwt = false
